doit:
	./do-it.sh                                                  \
	    test-repo                                               \
	    servlex.xml                                             \
	    servlex                                                 \
	    cases                                                   \
	    webapps/filters/dist/filters-webapp-0.1.0.xaw           \
	    webapps/filters-app/dist/filters-app-webapp-0.1.0.xaw   \
	    webapps/mapping/dist/mapping-webapp-0.2.0.xaw           \
	    webapps/xsltforms/dist/xsltforms-webapp-0.1.0.xaw       \
	    ../samples/hello-world/dist/hello-world-0.9.0dev.xaw    \
	    ../samples/webapp-manager/dist/webapp-manager-0.1.0.xaw
