doit:
	./do-it.sh \
	    test-repo \
	    servlex.xml \
	    servlex \
	    cases \
	    webapps/filters/dist/filters-webapp-0.1.0.xaw \
	    webapps/mapping/dist/mapping-webapp-0.2.0.xaw \
	    ../samples/hello-world/dist/hello-world-0.6.0dev.xaw 
