doit:
	../../do-it.sh \
	    repo \
	    svx-h2o.xml \
	    svx-h2o \
	    cases \
	    ../../../../../h2o/website/h2o-website/dist/h2o-website-0.5.0pre1.xaw \
	    ../../../../../xlibs/webapp-tools/dist/webapp-tools-0.3.0pre1.xaw \
	    ../../../../../xlibs/serial/dist/serial-0.4.0pre1.xar \
	    ../../../../../xlibs/fxsl/build/fxsl-1.0.xar \
	    ../../../../http-client/saxon/build/expath-http-client-saxon-0.10.0.xar \
	    ../../../../../xquery/xqts-browser/dist/xqts-browser-0.5.0pre1.xaw \
	    ../../../../../xquery/xqts-suite/dist/xqts-suite-1.0.3.xar \
	    ../../../../zip/saxon/build/expath-zip-saxon-0.6.0.xar \
	    ../../../../../xlibs/google-apis/dist/google-apis-0.3.0.xar
